name: dio_cache
description: A plugin for dio that caches responses for better optimization and offline data access.
version: 0.4.0-beta
homepage: https://github.com/aloisdeniel/dio_cache
author: aloisdeniel <alois.deniel@outlook.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  meta: ^1.2.4
  logging: ^0.11.4
  dio: ^3.0.10
  path: ^1.7.0
  uuid: ^2.2.2

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
